### ISSUE TITLE
配置了代理为什么还不能访问提示404

### ISSUE THREAD

**Issue by JavaScript-zt** [yupingyong/kite.gateway#22]
![企业微信截图_16613121421327](https://user-images.githubusercontent.com/19992219/186323030-268c69ee-b54d-450b-8d7e-3f8a980f58da.png)

![企业微信截图_16613121992315](https://user-images.githubusercontent.com/19992219/186323121-6ae3b84c-eda3-4d36-99b6-40b0cdeec67b.png)

**Comment by yupingyong** [comment]
你的 tank 路由关联的站点 有启动吗?

**Comment by JavaScript-zt** [comment]
你好，肯定启动了这个站点时能访问的
那我换成百度的地址

![image](https://user-images.githubusercontent.com/19992219/187581042-31455b3b-0850-420d-a5cf-66025fbed85a.png)

![image](https://user-images.githubusercontent.com/19992219/187581094-ad1e7e2f-7aa2-4ec6-8365-ec903c0f19e3.png)

仍然是404

**Comment by yupingyong** [comment]
能提供下 网关打印出来的日志呢

**Comment by JavaScript-zt** [comment]
我是部署在IIS上的，站点没有产生任何日志，但是能访问，输出 hello world!!!

**Comment by yupingyong** [comment]
IIS 部署我确实没有去考虑过,我增加一下 输出日志到文件里面
方便排查问题,我也试试IIS下部署

**Comment by JavaScript-zt** [comment]
谢谢，你这个封装yarp的创意非常好，如果搞好了肯定有很多开发使用。

**Comment by yupingyong** [comment]
谢谢你的支持,我开源出来就是希望有人能对这个产品提出问题来,才能更好的去完善它,让它变的更稳健、更实用
满足中小项目应用场景的需求

**Comment by yupingyong** [comment]
我在IIS下 尝试了 应该没问题 
![image](https://user-images.githubusercontent.com/29831143/187612334-41ca18d8-f4b7-44a4-a6ba-92d1e4b03b14.png)
![image](https://user-images.githubusercontent.com/29831143/187612409-631da6fe-a333-43e0-a54f-8744b647fdf1.png)
![image](https://user-images.githubusercontent.com/29831143/187612460-a1bb620e-f5d7-4874-aa8f-53b39c4e61cc.png)
![image](https://user-images.githubusercontent.com/29831143/187612495-1c720226-87ae-47b8-92e3-8cf89e1ea875.png)

**Comment by yupingyong** [comment]
你那边 可以获取下最新的源代码再试试看

**Comment by JavaScript-zt** [comment]
bug:  在 ReverseProxyDatabaseStore.cs 第38行：
如果 route.RouteTransforms count为0，
 transforms.Add(transformData);  这行就会给transforms 对象增加一个空Dictionary<string, string>结构进去，这时候就会报错。
