### ISSUE TITLE
性能优化 [正则表达式]

### ISSUE THREAD

**Issue by xljiulang** [yupingyong/kite.gateway#4]
### 问题描述
在[KiteAuthorizationMiddleware line 56](https://github.com/yupingyong/kite.gateway/blob/master/src/Kite.Gateway.Hosting/Middlewares/KiteAuthorizationMiddleware.cs#L56)存在如下代码：
```
var reg = new Regex(whitelist.FilterText);
if(reg.IsMatch(requestPath) && reqeustMethod == whitelist.RequestMethod)
```
根据我的Benchmark经验，new Regex的方法性能远低，不适合在中间件这种性能要求高的场合使用。

此处应该改为Regex静态方法，或者在whitelist里面，在构造FilterText的时候，同时构造出一个已编译好的Regex，在中间件直接使用此编译好的Regex。

此外，个人建议不使用完整的正则表达式做匹配，使用*来匹配任意就够用。

**Comment by yupingyong** [comment]
本来想着设计方案是可能有类似比较特殊一点的需求
不过我看你给到的建议是非常好的,我会进行改进
谢谢你的支持
