### ISSUE TITLE
无作用的配置委托[Options]

### ISSUE THREAD

**Issue by xljiulang** [yupingyong/kite.gateway#5]
#### 问题描述
https://github.com/yupingyong/kite.gateway/blob/master/src/Kite.Gateway.Hosting/HostingModule.cs#L58
```c#
  private void ConfigureCore(ServiceConfigurationContext context)
  {
      context.Services.Configure<AuthenticationOption>(opt => { });
      ...
      context.Services.Configure<TokenValidationParameters>(opt => { });
  }
```
` context.Services.Configure<AuthenticationOption>(opt => { })`本质上是向di注册了Microsoft.Extensions.Options.IConfigureOptions<AuthenticationOption>的实现实例，但这个实例的Configure方法什么也不用，所以目前不如直接移除这个ConfigureCore方法。

**Comment by yupingyong** [comment]
是的,默认是注册了
是为了方便后台管理运行过程中动态向网关推送配置信息而这么处理
