### ISSUE TITLE
KiteExternalMiddleware的设计咨询

### ISSUE THREAD

**Issue by xljiulang** [yupingyong/kite.gateway#6]
### 问题描述
目前看不懂KiteExternalMiddleware和MiddlewareOption是要解决什么问题，但目前有已下疑问：

* 为何每次请求都要排序MiddlewareOption?
* 为何使用IHttpClientFactory来转发？

#### MiddlewareOption排序
这个中间件注入了`IOptions<List<MiddlewareOption>> options`，我们知道，`IOptions<T>`是单例的服务，只会构造一次`List<MiddlewareOption>`，所以在构造器把List<MiddlewareOption>排序一次并缓存到字段，中间件执行时，`foreach (var middleware in _middlewares.Where(x => x.UseState).OrderByDescending(x => x.ExecWeight).ToList())`就不需要排序了，况且这里后面的ToList，又2次创建了List。。。

#### IHttpClientFactory转发
YARP的核心就是做转发，且YARP是杜绝使用HttpClient的，原因是HttpClient设计为等待响应完成，这与YARP想要的边接收边传输是相违背的。这里是否能使用YARP的`Yarp.ReverseProxy.Forwarder.IHttpForwarder`来完成这个功能呢？

**Comment by yupingyong** [comment]
为何每次请求都要排序MiddlewareOption？

**Comment by yupingyong** [comment]
为何每次请求都要排序MiddlewareOption?

**Comment by yupingyong** [comment]
为何每次请求都要排序MiddlewareOption?
这个确实属于我这边低级错误了,我会修正这个问题.

为何使用IHttpClientFactory来转发？
我原本是考虑过使用 Yarp.ReverseProxy.Forwarder.IHttpForwarder来直接转发的,但后来想到了中间件响应结果需要做单独处理.最开始设计的时候中间件 我并没有放到  proxyPipeline.UseMiddleware<KiteExternalMiddleware>();去启用组件 而是直接 app.UseMiddleware<KiteExternalMiddleware>();
所以这也是个需要改进的地方
