### ISSUE TITLE
缺少x-forwarded配置与处理[安全隐患]

### ISSUE THREAD

**Issue by xljiulang** [yupingyong/kite.gateway#8]
在反向代理里，每一层反向代理都需要追加x-forwarded转换头，为上游服务提供请求协议、ip、host等信息，当然YARP已内置默认这么做了；但做为最外层网关时，默认情况下应该无条件的丢弃外部请求传入的x-forwarded，以保证上游服务收到的x-forwarded不是请求者伪造（或部分伪造）的，除非显式的网关配置请求IP为可信的白名单，才可能接收和使用外部请求传入的x-forwarded的值。

你可以试试在外部请求到出名的开源kong网关，请求头添加x-forwarded-for: 1.2.3.4，在你的kong下的服务观察收到的请求头x-forwarded-for的值，发现1.2.3.4默认配置下是被kong丢弃的，这是为了安全。

**Comment by yupingyong** [comment]
好的 新的版本会解决这个问题
