### ISSUE TITLE
简化项目[建议]

### ISSUE THREAD

**Issue by xljiulang** [yupingyong/kite.gateway#9]
### 移除abp
本项目里，完全用不着，因为没有众多且隔离的业务模块，原生asp.netcore完全满足且降低不必要的复杂度；

### 移除mysql
本项目里，使用sqlite完全满足了，sqlite不需要独立的服务引擎，部署和维护更方便。

### 完善middleware
除了最后一步需要yarp变换与转发，其它功能完全可以开发为asp.netcore middleware，精心编排这些middleware，高性能和可维护度都可以兼得。

**Comment by yupingyong** [comment]
Abp不会考虑移除
Sqlite数据库已经采用更换(本来我最开始使用的是Sqlite,后面切换到mysql上去的)
